
platform :ios, '10.0'

def app_pods
  # Pods for Effeh
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
end

target 'Effeh' do
  use_frameworks!

  # Pods for Effeh
  app_pods

  target 'EffehTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EffehUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EffehBoard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EffehBoard
  app_pods

end
